### ISSUE TITLE
The 404 page has broken links

### ISSUE THREAD

**Issue by ViralBShah** [JuliaLang/www.julialang.org#555]
https://julialang.org/404

**Comment by StefanKarpinski** [comment]
If I actually go to a non-existent page, I don't get redirected to the 404 page either, I get this:

<img width="1355" alt="Screen Shot 2020-01-11 at 7 39 53 PM" src="https://user-images.githubusercontent.com/153596/72212439-2bac0580-34aa-11ea-908f-c938ae75bcc3.png">

**Comment by logankilpatrick** [comment]
Fixed

**Comment by logankilpatrick** [comment]
Thanks for reporting!

**Comment by StefanKarpinski** [comment]
My issue still seems to exist. Should I open a separate issue?

**Comment by logankilpatrick** [comment]
I think it may take a few moments to push out but it's working on my computer at the moment. https://julialang.org/hihihi shows the correct 404 page

**Comment by logankilpatrick** [comment]
<img width="1552" alt="Screen Shot 2020-01-11 at 8 13 38 PM" src="https://user-images.githubusercontent.com/35577566/72212703-dcb49f00-34ae-11ea-843f-f87f8ad3051a.png">

**Comment by StefanKarpinski** [comment]
Weird, I thought I'd posted something here... I can confirm that works. The page I had tried before must have gotten cached somewhere.

**Comment by logankilpatrick** [comment]
This is a weird one @StefanKarpinski https://julialang.org/hihihi gives the right error 404 screen but https://julialang.org/blog/hi gives the broken one.

**Comment by abhishalya** [comment]
I'll get this fixed asap.

**Comment by ViralBShah** [comment]
The problem is absolute paths for locating the css:
```
<link rel="stylesheet" href="./v2/css/bootstrap.min.css" />
<link rel="stylesheet" href="./v2/css/app.css" />
<link rel="stylesheet" href="./v2/css/fonts.css" />
```

**Comment by logankilpatrick** [comment]
This is still an issue

**Comment by logankilpatrick** [comment]
@ViralBShah @StefanKarpinski @abhishalya I think this is finally fixed. Can you all check and make sure that none of the links in this thread give the broken 404 page? Thanks!

**Comment by ViralBShah** [comment]
Working fine.

**Comment by abhishalya** [comment]
Any idea how this was fixed? I had merged a PR but it didn't fix it at that time.

**Comment by logankilpatrick** [comment]
Switching the base url to include “https://“.

**Comment by abhishalya** [comment]
Damn
